### ISSUE TITLE
Add times of images used in averaged to the subtraction FITS image header

### ISSUE THREAD

**Issue by jburkepile** [NCAR/kcor-pipeline#334] opened 2023-05-04 19:53 UTC
The new subtraction code creates a subtraction every 30 seconds. If there are no data gaps, the subtraction is created by averaging 2 adjacent images (<=16 seconds apart) for both the foreground and the background image.

Please save the times used in the averages in the fits header. 
- [ ] Create variables to store 2 image times in hh:mm:ss
- [ ] Create a string that stores the 2 image times 'hh:mm:ss  hh:mm:ss'
- [ ] Use `FXADDPAR` to write the label to a new fits keyword `AVGTIME0`, e.g.:

           fxaddpar, goodheader,'AVGTIME0', labelstring,' Img times used in avg'

**Comment by jburkepile** [comment] 2023-05-04 21:26
MIke's question:  So there should be an AVGTIME0 (for the background image) and an AVGTIME1 (for the foreground image)?
Mike: thanks asking that. I left that out entirely. You are exactly right. AVGTIME0 can be the 2 times used to make the background image and AVGTIME1 the 2 times used to make the foreground image.   Obviously when there is a data gap, there will be only 1 image (no averaging). 
Thanks very much!

**Comment by mgalloy** [comment] 2023-05-05 14:56
Is this issue the same as #335?

**Comment by mgalloy** [comment] 2023-05-05 19:37
Closing as a duplicate of #335.

**Closed by mgalloy** 2023-05-05 19:37 UTC
Labels: enhancement
